# This is a basic workflow to help you get started with Actions

name: Manual_Deployment

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab 
  workflow_dispatch:
   

# A workflow run is made up of one or more jobs that can run sequentially or in parallel -
jobs:
  jobs:
  deploy:
    steps:
      - name: Trigger AWS CodePipeline
        uses: zulhfreelancer/aws-codepipeline-action@vX.X.X
        with:
          aws-region: "ap-southeast-1"
          aws-access-key: ${{ secrets.AWS_PIPELINE_ACCESS_KEY }}
          aws-secret-key: ${{ secrets.AWS_PIPELINE_SECRET_KEY }}
          pipeline-name: "nftmarketplace-backend-pipeline"
